pluginManagement {
    repositories {
        maven {
            name = 'NeoForge'
            url = 'https://maven.neoforged.net/releases'
        }
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositories {
        maven {
            name = 'NeoForge'
            url = 'https://maven.neoforged.net/releases'
        }
        maven {
            name = 'LDTTeam'
            url = 'https://ldtteam.jfrog.io/ldtteam/modding/'
            content {
                includeGroup 'com.ldtteam'
            }
        }
        maven {
            name = 'CurseMaven'
            url = 'https://cursemaven.com'
            content {
                includeGroup 'curse.maven'
            }
        }
        mavenCentral()
    }
}

rootProject.name = 'minecolonies-history'
