modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecolonies"
type = "required"
versionRange = "[1.1.1403,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "structurize"
type = "required"
versionRange = "[1.0.832,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "blockui"
type = "required"
versionRange = "[1.0.199,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "domum_ornamentum"
type = "required"
versionRange = "[1.0.223,)"
ordering = "AFTER"
side = "BOTH"
